FROM lmsysorg/sglang:latest

# Set model name or path (Hugging Face, local, etc.)
ARG MODEL_PATH="TinyLlama/TinyLlama-1.1B-Chat-v1.0"
ENV MODEL_PATH=$MODEL_PATH
ENV HF_HOME=/root/.cache/huggingface

# Pre-download the model weights
RUN hf download ${MODEL_PATH} --local-dir /models/${MODEL_PATH}

CMD ["/bin/bash"]
